title       = "europeana"
baseURL     = "https://europeana-cli.tamnd.com/"
description = "A command line for europeana."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/europeana-cli"
